package com.example.pizza.controller;

import com.example.pizza.model.Customer;
import com.example.pizza.repository.CustomerRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/customer") // This means URL's start with /demo (after
public class CustomerController {
    // Autowired means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    @Autowired
    private CustomerRepository customerRepository;


    @GetMapping(path = "/all")
    public @ResponseBody
    Iterable<Customer> getAll() {
        // This returns a JSON or XML with the users
        return customerRepository.findAll();
    }


    @PostMapping(path = "/add") // Map ONLY POST Requests
    public @ResponseBody
    String addNewUser(
            @RequestParam String firstName,
            @RequestParam String lastName,
            @RequestParam String address,
            @RequestParam Long phoneNumber,
            @RequestParam int zipCode

    ) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        Customer c = new Customer(firstName, lastName, address, phoneNumber, zipCode);
        customerRepository.save(c);
        return "Saved";
    }

}
